[package]
name = "protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.2"
prost-types = "0.13.2"
serde_json = "1.0.128"
vc_signing = {path = ".."}
url = "2.5.2"
chrono = "0.4.38"

[build-dependencies]
prost-build = "0.13.2"
