[package]
name = "get_github_schema"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
serde_json = "1.0.127"
reqwest = { version = "0.12.7", features = ["json"] }
serde_yaml = "0.9.34"
tokio = { version = "1.42.0", features = ["macros"] }

